workflows:
  android-debug:
    name: Control Medidores - APK Debug
    max_build_duration: 30
    instance_type: linux
    scripts:
      - name: Compilar APK nativo
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
